# Generated by Django 4.1.5 on 2023-01-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='users.myuser', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='users.myuser', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task_manager.LabelToTask', to='task_manager.labels', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_manager.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='labeltotask',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task_manager.labels'),
        ),
        migrations.AddField(
            model_name='labeltotask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
