# Generated by Django 4.1.4 on 2023-01-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
    ]
