# Generated by Django 4.1.5 on 2023-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_labels_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task_manager.LabelToTask', to='task_manager.labels', verbose_name='Метки'),
        ),
    ]
