# Generated by Django 4.1.5 on 2023-01-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_alter_task_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_ptr',
        ),
    ]
